import { NextRequest, NextResponse } from "next/server";

// GitHub Actions workflow file content - Uses repository_dispatch with Gemini CLI
const WORKFLOW_CONTENT = `name: Generate Code with Gemini

on:
  # Triggered via API from Zyntara
  repository_dispatch:
    types: [generate-code]
  
  # Allow manual trigger for testing
  workflow_dispatch:
    inputs:
      test_mode:
        description: 'Run in test mode'
        required: false
        default: 'false'

jobs:
  generate-code:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      pull-requests: write
    
    steps:
      - name: Log trigger info
        run: |
          echo "🚀 Workflow triggered!"
          echo "Event: \${{ github.event_name }}"
      
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Mask API key
        if: github.event.client_payload.api_key
        run: |
          # Mask the API key so it won't appear in logs
          echo "::add-mask::\${{ github.event.client_payload.api_key }}"
      
      - name: Save feature spec
        if: github.event_name == 'repository_dispatch'
        env:
          FEATURE_JSON: \${{ toJson(github.event.client_payload.feature) }}
        run: |
          mkdir -p .gemini-specs
          echo "\$FEATURE_JSON" > .gemini-specs/current-feature.json
          echo "📋 Feature spec saved:"
          cat .gemini-specs/current-feature.json | jq 'del(.annotatedImage, .screenshots)' 2>/dev/null || echo "(spec saved)"
      
      - name: Extract feature info
        id: feature-info
        run: |
          if [ -f ".gemini-specs/current-feature.json" ]; then
            TITLE=\$(cat .gemini-specs/current-feature.json | jq -r '.title // "Unknown"' | head -c 50)
            TYPE=\$(cat .gemini-specs/current-feature.json | jq -r '.type // "feature"')
          else
            TITLE="test-feature"
            TYPE="feature"
          fi
          echo "title=\$TITLE" >> \$GITHUB_OUTPUT
          echo "type=\$TYPE" >> \$GITHUB_OUTPUT
          echo "branch_name=auto-gen/\${{ github.run_number }}-\$TYPE" >> \$GITHUB_OUTPUT
          echo "📝 Title: \$TITLE, Type: \$TYPE"
      
      - name: Generate code with Gemini API
        if: github.event_name == 'repository_dispatch'
        env:
          # API key from trigger (masked above) or from repository secrets
          GEMINI_API_KEY: \${{ github.event.client_payload.api_key || secrets.GEMINI_API_KEY }}
        run: |
          if [ -z "\$GEMINI_API_KEY" ]; then
            echo "⚠️ No GEMINI_API_KEY found."
            echo "Either pass it via the trigger or add it to repository secrets."
            exit 1
          fi
          echo "🤖 Generating code with Gemini..."
          node .github/scripts/generate-with-api.js
      
      - name: Apply generated code
        if: github.event_name == 'repository_dispatch'
        run: |
          if [ -f ".gemini-specs/output.md" ]; then
            echo "📦 Applying generated code..."
            node .github/scripts/apply-changes.js .gemini-specs/output.md
          else
            echo "⚠️ No output file found"
          fi
      
      - name: Create Pull Request
        if: github.event_name == 'repository_dispatch'
        uses: peter-evans/create-pull-request@v6
        with:
          token: \${{ secrets.GITHUB_TOKEN }}
          commit-message: 'feat: \${{ steps.feature-info.outputs.title }}'
          branch: \${{ steps.feature-info.outputs.branch_name }}
          delete-branch: true
          title: '🤖 [\${{ steps.feature-info.outputs.type }}] \${{ steps.feature-info.outputs.title }}'
          body: |
            ## Auto-Generated Code
            
            This PR was automatically generated by **Gemini** based on the feature specification.
            
            ### Feature Details
            - **Type:** \${{ steps.feature-info.outputs.type }}
            - **Title:** \${{ steps.feature-info.outputs.title }}
            
            ### ⚠️ Review Checklist
            - [ ] Code follows project conventions
            - [ ] All acceptance criteria met
            - [ ] No unintended side effects
            - [ ] Tests pass
            
            ---
            *Generated by Zyntara UX Analyzer*
          labels: |
            auto-generated
            needs-review
`;

// Script to generate code using Gemini API directly (fallback when CLI not available)
const GENERATE_SCRIPT = `const fs = require('fs');
const path = require('path');

// Scan repository to understand codebase structure
function scanRepository() {
  const structure = { directories: [], files: [], keyFiles: {} };
  const ignoreDirs = ['node_modules', '.git', '.next', 'dist', 'build', '.gemini-specs'];
  const keyFilePatterns = ['package.json', 'tsconfig.json', 'next.config', 'tailwind.config'];
  const codeExtensions = ['.ts', '.tsx', '.js', '.jsx', '.css', '.scss'];
  
  function scan(dir, depth = 0) {
    if (depth > 3) return; // Limit depth
    try {
      const items = fs.readdirSync(dir);
      for (const item of items) {
        if (ignoreDirs.includes(item) || item.startsWith('.')) continue;
        const fullPath = path.join(dir, item);
        const stat = fs.statSync(fullPath);
        
        if (stat.isDirectory()) {
          structure.directories.push(fullPath);
          scan(fullPath, depth + 1);
        } else if (stat.isFile()) {
          structure.files.push(fullPath);
          // Capture key config files
          if (keyFilePatterns.some(p => item.includes(p))) {
            try {
              structure.keyFiles[fullPath] = fs.readFileSync(fullPath, 'utf8').slice(0, 2000);
            } catch (e) {}
          }
        }
      }
    } catch (e) {}
  }
  
  scan('.');
  return structure;
}

// Get sample files from each directory to understand code patterns
function getSampleCode(structure) {
  const samples = [];
  const seenDirs = new Set();
  const codeExtensions = ['.ts', '.tsx', '.js', '.jsx'];
  
  for (const file of structure.files) {
    const ext = path.extname(file);
    const dir = path.dirname(file);
    
    // Get one sample per directory
    if (codeExtensions.includes(ext) && !seenDirs.has(dir)) {
      try {
        const content = fs.readFileSync(file, 'utf8');
        if (content.length < 5000) { // Only include smaller files
          samples.push({ path: file, content: content.slice(0, 3000) });
          seenDirs.add(dir);
        }
      } catch (e) {}
    }
    
    if (samples.length >= 5) break; // Limit samples
  }
  
  return samples;
}

async function generateCode() {
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) {
    console.error('❌ GEMINI_API_KEY not set');
    process.exit(1);
  }

  try {
    const spec = JSON.parse(fs.readFileSync('.gemini-specs/current-feature.json', 'utf8'));
    console.log('📋 Feature:', spec.title);
    
    // Scan repository for context
    console.log('🔍 Scanning repository...');
    const repoStructure = scanRepository();
    console.log('  Found', repoStructure.files.length, 'files in', repoStructure.directories.length, 'directories');
    
    // Get sample code to understand patterns
    const sampleCode = getSampleCode(repoStructure);
    console.log('  Loaded', sampleCode.length, 'sample files for context');
    
    // Get code context from affected files if specified
    const affectedFiles = [];
    if (spec.affected_files) {
      for (const file of spec.affected_files) {
        if (fs.existsSync(file)) {
          affectedFiles.push({ path: file, content: fs.readFileSync(file, 'utf8') });
          console.log('  ✓ Loaded affected file:', file);
        }
      }
    }
    
    const prompt = buildPrompt(spec, repoStructure, sampleCode, affectedFiles);
    
    console.log('🤖 Calling Gemini API...');
    const response = await fetch('https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash-exp:generateContent?key=' + apiKey, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        contents: [{ parts: [{ text: prompt }] }],
        generationConfig: { temperature: 0.2, maxOutputTokens: 8192 }
      })
    });
    
    const data = await response.json();
    const text = data.candidates?.[0]?.content?.parts?.[0]?.text || '';
    
    if (!text) {
      console.error('❌ No response from Gemini');
      console.log('Response:', JSON.stringify(data, null, 2));
      process.exit(1);
    }
    
    fs.writeFileSync('.gemini-specs/output.md', text);
    console.log('✅ Generated output saved');
    
  } catch (error) {
    console.error('❌ Error:', error);
    process.exit(1);
  }
}

function buildPrompt(spec, repoStructure, sampleCode, affectedFiles) {
  const taskType = spec.type === 'feature' ? 'new feature' : 'bug fix';
  
  // Build repository structure overview
  const structureOverview = repoStructure.directories.slice(0, 20).join('\\n');
  
  // Build key files context (package.json, config files)
  const keyFilesContext = Object.entries(repoStructure.keyFiles)
    .map(([file, content]) => '### ' + file + '\\n\\\`\\\`\\\`json\\n' + content + '\\n\\\`\\\`\\\`')
    .join('\\n\\n');
  
  // Build sample code context
  const sampleContext = sampleCode
    .map(s => '### ' + s.path + '\\n\\\`\\\`\\\`\\n' + s.content + '\\n\\\`\\\`\\\`')
    .join('\\n\\n');
  
  // Build affected files context
  const affectedContext = affectedFiles
    .map(f => '### ' + f.path + ' (TO BE MODIFIED)\\n\\\`\\\`\\\`\\n' + f.content + '\\n\\\`\\\`\\\`')
    .join('\\n\\n');
  
  return \`You are a senior developer working on an existing codebase. Your task is to implement a \${taskType}.

**IMPORTANT:** You are integrating into an EXISTING project. Study the repository structure, coding patterns, and conventions below before generating any code. Your output must seamlessly fit into this codebase.

## Repository Structure
\\\`\\\`\\\`
\${structureOverview}
\\\`\\\`\\\`

## Project Configuration
\${keyFilesContext || 'No config files found'}

## Existing Code Patterns (Study these carefully!)
\${sampleContext || 'No sample code available'}

## Files to Modify
\${affectedContext || 'No specific files specified - determine best location'}

---

## Task: \${spec.title}
**Type:** \${spec.type}

## Description
\${spec.description}

## Technical Specification
\${spec.spec || 'No detailed spec provided'}

## Requirements
1. **MUST** follow the existing code patterns shown above
2. **MUST** use the same styling conventions (Tailwind, CSS modules, etc.)
3. **MUST** use the same component patterns
4. **MUST** include all necessary imports
5. **MUST** be production-ready code
6. Add helpful comments where appropriate

## Output Format
For EACH file you modify or create, use this EXACT format:

FILE: path/to/file.tsx
\\\`\\\`\\\`typescript
// Complete file content here
\\\`\\\`\\\`

Generate the implementation that integrates seamlessly with this codebase:\`;
}

generateCode();
`;

// Script to apply generated code changes
const APPLY_SCRIPT = `const fs = require('fs');
const path = require('path');

const outputFile = process.argv[2] || '.gemini-specs/output.md';

if (!fs.existsSync(outputFile)) {
  console.log('No output file found at', outputFile);
  process.exit(0);
}

const content = fs.readFileSync(outputFile, 'utf8');
const pattern = /FILE:\\s*(.+?)\\n\\\`\\\`\\\`(?:typescript|tsx|jsx|javascript|css|scss|json|html)?\\n([\\s\\S]+?)\\\`\\\`\\\`/g;

let match;
let count = 0;

while ((match = pattern.exec(content)) !== null) {
  const filePath = match[1].trim();
  const fileContent = match[2].trim();
  
  const dir = path.dirname(filePath);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
    console.log('📁 Created directory:', dir);
  }
  
  fs.writeFileSync(filePath, fileContent + '\\n');
  console.log('✓ Updated:', filePath);
  count++;
}

console.log('\\n✅ Applied', count, 'file(s)');
`;

// Combined for backward compatibility
const SCRIPT_CONTENT = GENERATE_SCRIPT;

async function createOrUpdateFile(
  token: string,
  repo: string,
  path: string,
  content: string,
  branch: string,
  message: string
) {
  // Check if file exists
  const existsResponse = await fetch(
    `https://api.github.com/repos/${repo}/contents/${path}?ref=${branch}`,
    {
      headers: {
        Authorization: `Bearer ${token}`,
        Accept: "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28"
      }
    }
  );

  let sha: string | undefined;
  if (existsResponse.ok) {
    const existingFile = await existsResponse.json();
    sha = existingFile.sha;
  }

  // Create or update file
  const response = await fetch(
    `https://api.github.com/repos/${repo}/contents/${path}`,
    {
      method: "PUT",
      headers: {
        Authorization: `Bearer ${token}`,
        Accept: "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28"
      },
      body: JSON.stringify({
        message,
        content: Buffer.from(content).toString("base64"),
        branch,
        sha
      })
    }
  );

  if (!response.ok) {
    const error = await response.json();
    throw new Error(`Failed to create ${path}: ${error.message}`);
  }

  return response.json();
}

export async function POST(req: NextRequest) {
  try {
    const { token, repo, branch } = await req.json();

    if (!token || !repo) {
      return NextResponse.json({ error: "Token and repository are required" }, { status: 400 });
    }

    console.log(`Setting up workflow for ${repo}...`);

    // Create workflow file
    await createOrUpdateFile(
      token,
      repo,
      ".github/workflows/auto-code-gen.yml",
      WORKFLOW_CONTENT,
      branch,
      "chore: Add auto-code-gen workflow"
    );
    console.log("✓ Created workflow file");

    // Create generate script (API fallback)
    await createOrUpdateFile(
      token,
      repo,
      ".github/scripts/generate-with-api.js",
      GENERATE_SCRIPT,
      branch,
      "chore: Add Gemini API generation script"
    );
    console.log("✓ Created generate-with-api.js");

    // Create apply changes script
    await createOrUpdateFile(
      token,
      repo,
      ".github/scripts/apply-changes.js",
      APPLY_SCRIPT,
      branch,
      "chore: Add code apply script"
    );
    console.log("✓ Created apply-changes.js");

    // Create .gemini-specs directory
    await createOrUpdateFile(
      token,
      repo,
      ".gemini-specs/.gitkeep",
      "# Gemini CLI specifications directory\n",
      branch,
      "chore: Create .gemini-specs directory"
    );
    console.log("✓ Created .gemini-specs directory");

    return NextResponse.json({
      success: true,
      message: "Workflow setup complete! Don't forget to add GEMINI_API_KEY to your repository secrets."
    });

  } catch (error: any) {
    console.error("Setup error:", error);
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}

